---
name: Test
on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Install containerd; run go test
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    
    - name: Download containerd
      run: curl -L --output /tmp/containerd-1.3.4.linux-amd64.tar.gz https://github.com/containerd/containerd/releases/download/v1.3.4/containerd-1.3.4.linux-amd64.tar.gz
    
    - name: Install/start containerd
      run: |
        sudo sh -c 'tar -xvz -f /tmp/containerd-1.3.4.linux-amd64.tar.gz -C /usr/local/ && mkdir -p /etc/containerd/ && containerd config default > /etc/containerd/config.toml was && chmod +x /usr/local/bin/containerd* /usr/local/bin/ctr'
        sudo containerd &> /tmp/containerd.log &
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: go get
      run: go get -v -t -d ./...
    
    - name: Run tests
      run: |
        sudo go test -v ./...

    - name: Output containerd info and logs on failure
      if: ${{ failure() }}
      run: |
        sudo ctr ns ls
        sudo ctr -n clamor-testing i ls
        sudo ctr -n clamor-testing c ls
        sudo ctr -n clamor-testing snapshot ls
        sudo ctr -n clamor-testing t ls
        sudo cat /tmp/containerd.log
